name: Build and Test
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - run: |
         git clone https://github.com/gmicroul/opensuse-sdm845-images
         cd opensuse-sdm845-images
         #sudo chown runner:docker opensuse-sdm845-images/openSUSE-Tumbleweed-ARM-PHOSH-oneplus6.aarch64.raw.xz
         pwd
         ls -ltr
         whoami
         su - runner -c "./download-image.sh"
         pwd
         ls -ltr
         su - runner -c "./mount-images.sh"
         su - runner -c "./bootloader.sh"
         su - runner -c "./umount-images.sh"
         su - runner -c "./extract-rootfs.sh"
         
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'oneplus6'
        path: './*.img'
        
