name: Build and Test
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - run: |
         pwd
         ls -ltr
         whoami
         sudo bash /home/runner/work/opensuse-sdm845-images/opensuse-sdm845-images/download-image.sh
         sudo bash /home/runner/work/opensuse-sdm845-images/opensuse-sdm845-images/mount-image.sh
         sudo bash /home/runner/work/opensuse-sdm845-images/opensuse-sdm845-images/bootloader.sh
         sudo bash /home/runner/work/opensuse-sdm845-images/opensuse-sdm845-images/umount-image.sh
         sudo bash /home/runner/work/opensuse-sdm845-images/opensuse-sdm845-images/extract-rootfs.sh
         
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'oneplus6'
        path: './*.img'
        
