name: Build and Test
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - run: |
         pwd
         ls -ltr
         whoami
         bash download-image.sh
         pwd
         ls -ltr
         sudo bash mount-images.sh
         sudo bash bootloader.sh
         sudo bash umount-images.sh
         sudo bash extract-rootfs.sh
         
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'oneplus6'
        path: './*.img'
        
