name: Build and Test loop3
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - run: |
        sudo apt update
        sudo apt install abootimg img2simg
        git clone https://github.com/osm0sis/mkbootimg
        cd mkbootimg
        make
        sudo make install
        cd ..
        sudo bash all.sh
        ls -ltrh
         
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'openSUSE-Tumbleweed-ARM-PHOSH-oneplus6'
        path: './*.img'
        
    #- name: Download the release artifact
    #  uses: actions/download-artifact@v4
    #  with:
    #    #name: release-${{ github.event.inputs.release }}
    #    name: 'openSUSE-Tumbleweed-ARM-PHOSH-oneplus6'
    #    path: './*.img' 

    - name: upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/openSUSE-Tumbleweed-ARM-PHOSH-oneplus6.zip
        asset_name: openSUSE-Tumbleweed-ARM-PHOSH-oneplus6.zip
        asset_content_type: application/zip
        
