name: Build and Test loop3
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - run: |
        sudo apt update
        sudo apt install abootimg img2simg
        git clone https://github.com/osm0sis/mkbootimg
        cd mkbootimg
        make
        sudo make install
        cd ..
        sudo bash all.sh
        ls -ltrh
         
      
    - name: Upload a Build Artifact
      id: compile
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'openSUSE-Tumbleweed-ARM-PHOSH-oneplus6'
        path: './*.img'
        run: |
          echo "::set-output name=status::success"
          ls -ltrh


    - name: Upload image to Release
      uses: ncipollo/release-action@main
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
        tag: opensuse_PHOSH_fajita_${{ env.COMPILE_STARTINGTIME }}
        artifacts: ./*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is opensuse image for fajita ${{ env.LINUX_GITURL }}
