name: Build and Test loop3
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - run: |
        sudo apt update
        sudo apt install abootimg android-sdk-libsparse-utils mkbootimg
        #git clone https://github.com/osm0sis/mkbootimg
        #cd mkbootimg
        #make
        #sudo make install
        #cd ..
        sudo bash all.sh
        ls -ltrh
        pwd
        mkdir tempzip
        mv *oneplus6*.img tempzip/
        cd tempzip
        zip openSUSE-Tumbleweed-ARM-PHOSH-oneplus6t.zip *oneplus6*.img
        pwd
        ls -ltrh
         
      
    - name: Upload a Build Artifact
      #id: compile
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'openSUSE-Tumbleweed-ARM-PHOSH-oneplus6'
        path: './tempzip/openSUSE-Tumbleweed-ARM-PHOSH-oneplus6t.zip'
      
    - name: Upload image to Release
      uses: ncipollo/release-action@main
      with:
        tag: opensuse_for_fajita-20251015
        artifacts: './tempzip/openSUSE-Tumbleweed-ARM-PHOSH-oneplus6t.zip'
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
            opensuse_for_fajita-20251015
